spring.application.name=notification-service
server.port=8081

# Configuración para PostgreSQL (alineada con el proyecto)
spring.datasource.url=jdbc:postgresql://postgres:5432/fullstack_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Eureka deshabilitado para desarrollo local
eureka.client.enabled=false

# Configuración RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nombre de la cola que escucharemos
app.rabbitmq.queue=notificaciones.queue